# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
	type= "sqlite"
    link= "./public/resource/db.db"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true